# Generated by Django 4.0.4 on 2024-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='level',
            field=models.CharField(default='Basic', max_length=50),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='saldo_mypay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'L'), ('Perempuan', 'P')], max_length=10),
        ),
    ]
