# Generated by Django 4.0.4 on 2024-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pengguna_level_pengguna_saldo_mypay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerja',
            name='jumlah_pesanan_selesai',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='kategori_pekerjaan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
