# Generated by Django 4.0.4 on 2024-11-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pekerja',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pekerja',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Pekerja',
        ),
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
